USE [IF5100_2022_B75934]

WITH EJEMPLO_CTE (EVENT_ID, EVENT_TYPE, AMOUNT, CUSTOMER_ACCOUNT_ID, COMPLETE_NAME, CLIENT_ID)  
AS  
(  
    SELECT E.EVENT_ID AS EVENT_ID, 
		   ET.EVENT_TYPE AS EVENT_TYPE, 
		   E.AMOUNT AS AMOUNT, 
		   CA.CUSTOMER_ACCOUNT_ID AS CUSTOMER_ACCOUNT_ID, 
		   CONCAT(CA.CUSTOMER_NAME,' ', CA.CUSTOMER_LAST_NAME) AS COMPLETE_NAME, 
		   C.CLIENT_ID AS CLIENT_ID
    FROM [FINANCIAL_DEPOSIT].[tb_EVENTS] E
		JOIN [FINANCIAL_DEPOSIT].[tb_EVENT_TYPES] ET
			ON E.[EVENT_TYPE_ID] = ET.[EVENT_TYPE_ID]
				JOIN [CUSTOMERS].[tb_CUSTOMER_ACCOUNTS] CA
					ON E.[CUSTOMER_ACCOUNT_ID] = CA.CUSTOMER_ACCOUNT_ID
						JOIN [CLI_COMMON].[tb_CLIENTS] C
							ON CA.CLIENT_ID = C.CLIENT_ID
    WHERE CA.[CUSTOMER_ACCOUNT_ID] = 1 
) SELECT * FROM EJEMPLO_CTE

CREATE TABLE dbo.INTERACTIONS
(
	INTERACTION_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,INTERACTION_DESCRIPTION VARCHAR(200) NOT NULL
	,LAST_MODIFIED_BY VARCHAR(25) DEFAULT SUSER_NAME()
	,LAST_MODIFIED_DATE DATETIME DEFAULT GETDATE()
)

CREATE TRIGGER Trigger_Insert
	ON [CUSTOMERS].[tb_COUNTRY]    
	FOR INSERT  
	AS 
		BEGIN TRY

			BEGIN TRANSACTION

				INSERT INTO dbo.INTERACTIONS
				(
					INTERACTION_DESCRIPTION
				)
				VALUES
				(
					'Inserción de un país en la tabla CUSTOMERS.COUNTRY'
				)

			COMMIT

		END TRY
		BEGIN CATCH
	
			ROLLBACK

		END CATCH

CREATE TRIGGER Trigger_Update
	ON [CUSTOMERS].[tb_COUNTRY]    
	FOR UPDATE  
	AS 
		BEGIN TRY

			BEGIN TRANSACTION

				INSERT INTO dbo.INTERACTIONS
				(
					INTERACTION_DESCRIPTION
				)
				VALUES
				(
					'Modificación de un país en la tabla CUSTOMERS.COUNTRY'
				)

			COMMIT

		END TRY
		BEGIN CATCH
	
			ROLLBACK

		END CATCH
  
CREATE TRIGGER Trigger_Delete
	ON [CUSTOMERS].[tb_COUNTRY]    
	FOR DELETE  
	AS 
		BEGIN TRY

			BEGIN TRANSACTION

				INSERT INTO dbo.INTERACTIONS
				(
					INTERACTION_DESCRIPTION
				)
				VALUES
				(
					'Eliminación de un país en la tabla CUSTOMERS.COUNTRY'
				)

			COMMIT

		END TRY
		BEGIN CATCH
	
			ROLLBACK

		END CATCH

SELECT * FROM dbo.INTERACTIONS
SELECT * FROM CUSTOMERS.tb_COUNTRY

INSERT INTO CUSTOMERS.tb_COUNTRY
(
	[COUNTRY_NAME],
	[IS_ACTIVE],
	[IS_DELETED],
	[LAST_MODIFIED_BY],
	[LAST_MODIFIED_DATE],
	[CONTINENT_ID]
)
VALUES
(
	'Hondurassss',
	1,
	0,
	SUSER_NAME(),
	GETDATE(),
	1
)

UPDATE CUSTOMERS.tb_COUNTRY
SET [COUNTRY_NAME] = 'Honduras'
WHERE [COUNTRY_NAME] = 'Hondurassss'

DELETE CUSTOMERS.tb_COUNTRY
WHERE [COUNTRY_NAME] = 'Honduras'
