USE IF5100_2022_B76090
GO

CREATE SCHEMA CLI_COMMON
CREATE SCHEMA CUSTOMERS
CREATE SCHEMA FINANCIAL_DEPOSIT
CREATE SCHEMA EVENT_HANDLER

CREATE TABLE CLI_COMMON.tb_CLIENTS
(
	 CLIENT_ID INT IDENTITY(1000,1) PRIMARY KEY
	,NAME VARCHAR(25) NOT NULL
	,INDUSTRY_DESC VARCHAR(100) NOT NULL
	,IS_ACTIVE BIT NOT NULL DEFAULT 1
	,IS_DELETED BIT DEFAULT 0
	,LAST_MODIFIED_BY VARCHAR(50) NULL
	,LAST_MODIFIED_DATE DATETIME NULL
)

CREATE TABLE CUSTOMERS.tb_CUSTOMER_ACCOUNTS
(
	CUSTOMER_ACCOUNT_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,CLIENT_ID INT NOT NULL--FOREIGN KEY TO TABLE tb_CLIENTS
	,CUSTOMER_NAME VARCHAR(25) NOT NULL
	,CUSTOMER_LAST_NAME VARCHAR(25) NOT NULL
	,IS_ACTIVE BIT NOT NULL DEFAULT 1
	,IS_DELETED BIT DEFAULT 0
	,LAST_MODIFIED_BY VARCHAR(50) NULL
	,LAST_MODIFIED_DATE DATETIME NULL
)

CREATE TABLE CUSTOMERS.tb_CREDIT_CARD
(
	CREDIT_CARD_ID INT PRIMARY KEY IDENTITY(5000,1) NOT NULL
	,CREDIT_CARD_NUMBER VARCHAR(16) UNIQUE NOT NULL
	,CREDIT_CARD_BRAND INT NOT NULL --1 VISA 2MC 3AMEX 
	,EXPIRATION_MONTH SMALLINT NOT NULL
	,EXPIRATION_YEAR SMALLINT NOT NULL
	,CVV SMALLINT NOT NULL
	,IS_ACTIVE BIT NOT NULL DEFAULT 1
	,IS_DELETED BIT DEFAULT 0
	,LAST_MODIFIED_BY VARCHAR(50) NULL
	,LAST_MODIFIED_DATE DATETIME NULL
)

CREATE TABLE CUSTOMERS.tb_PHONE
(
	PHONE_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,PHONE_NUMBER VARCHAR(15) NOT NULL
	,IS_ACTIVE BIT NOT NULL DEFAULT 1
	,IS_DELETED BIT DEFAULT 0
	,LAST_MODIFIED_BY VARCHAR(50) NULL
	,LAST_MODIFIED_DATE DATETIME NULL
)

CREATE TABLE CUSTOMERS.tb_COUNTRY
(
	COUNTRY_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,COUNTRY_NAME VARCHAR(50) NOT NULL
	,IS_ACTIVE BIT NOT NULL DEFAULT 1
	,IS_DELETED BIT DEFAULT 0
	,LAST_MODIFIED_BY VARCHAR(50) NULL
	,LAST_MODIFIED_DATE DATETIME NULL
)

CREATE TABLE CUSTOMERS.tb_STATE_PROVINCE
(
	STATE_PROVINCE_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,STATE_NAME VARCHAR(50) NOT NULL
	,COUNTRY_ID INT NOT NULL
	,IS_ACTIVE BIT NOT NULL DEFAULT 1
	,IS_DELETED BIT DEFAULT 0
	,LAST_MODIFIED_BY VARCHAR(50) NULL
	,LAST_MODIFIED_DATE DATETIME NULL
	,CONSTRAINT FK_COUNTRY FOREIGN KEY(COUNTRY_ID) REFERENCES CUSTOMERS.tb_COUNTRY(COUNTRY_ID) 
)

CREATE TABLE CUSTOMERS.tb_ADDRESS
(
	ADDRESS_ID INT PRIMARY KEY IDENTITY(1000,1)
	,DETAILS VARCHAR(200)
	,STATE_PROVINCE_ID INT NOT NULL
	,IS_ACTIVE BIT NOT NULL DEFAULT 1
	,IS_DELETED BIT DEFAULT 0
	,LAST_MODIFIED_BY VARCHAR(50) NULL
	,LAST_MODIFIED_DATE DATETIME NULL
	,CONSTRAINT FK_STATE_PROVINCE FOREIGN KEY (STATE_PROVINCE_ID) REFERENCES CUSTOMERS.tb_STATE_PROVINCE(STATE_PROVINCE_ID)
)

CREATE TABLE CUSTOMERS.tb_CUSTOMER_PHONES
(
	CUSTOMER_ACCOUNT_ID INT NOT NULL
	,PHONE_ID INT NOT NULL
	,IS_ACTIVE BIT NOT NULL DEFAULT 1
	,IS_DELETED BIT DEFAULT 0
	,LAST_MODIFIED_BY VARCHAR(50) NULL
	,LAST_MODIFIED_DATE DATETIME NULL
	,CONSTRAINT FK_CUST2 FOREIGN KEY(CUSTOMER_ACCOUNT_ID) REFERENCES CUSTOMERS.tb_CUSTOMER_ACCOUNTS(CUSTOMER_ACCOUNT_ID)
	,CONSTRAINT FK_PHONE FOREIGN KEY(PHONE_ID) REFERENCES CUSTOMERS.tb_PHONE(PHONE_ID)
	,CONSTRAINT PK_CUST_PHONE PRIMARY KEY(CUSTOMER_ACCOUNT_ID,PHONE_ID)
)

CREATE TABLE CUSTOMERS.tb_CUSTOMER_ADDRESSES
(
	CUSTOMER_ACCOUNT_ID INT NOT NULL
	,ADDRESS_ID INT NOT NULL
	,IS_ACTIVE BIT NOT NULL DEFAULT 1
	,IS_DELETED BIT DEFAULT 0
	,LAST_MODIFIED_BY VARCHAR(50) NULL
	,LAST_MODIFIED_DATE DATETIME NULL
	,CONSTRAINT FK_CUST1 FOREIGN KEY(CUSTOMER_ACCOUNT_ID) REFERENCES CUSTOMERS.tb_CUSTOMER_ACCOUNTS(CUSTOMER_ACCOUNT_ID)
	,CONSTRAINT FK_ADDRESS FOREIGN KEY(ADDRESS_ID) REFERENCES CUSTOMERS.tb_ADDRESS(ADDRESS_ID)
	,CONSTRAINT PK_CUST_ADDRESS PRIMARY KEY(CUSTOMER_ACCOUNT_ID,ADDRESS_ID)
)

CREATE TABLE CUSTOMERS.tb_CUSTOMER_CREDIT_CARDS
(
	CUSTOMER_ACCOUNT_ID INT NOT NULL
	,CREDIT_CARD_ID INT NOT NULL
	,IS_ACTIVE BIT NOT NULL DEFAULT 1
	,IS_DELETED BIT DEFAULT 0
	,LAST_MODIFIED_BY VARCHAR(50) NULL
	,LAST_MODIFIED_DATE DATETIME NULL
	,CONSTRAINT FK_CUST FOREIGN KEY(CUSTOMER_ACCOUNT_ID) REFERENCES CUSTOMERS.tb_CUSTOMER_ACCOUNTS(CUSTOMER_ACCOUNT_ID)
	,CONSTRAINT FK_CC FOREIGN KEY(CREDIT_CARD_ID) REFERENCES CUSTOMERS.tb_CREDIT_CARD(CREDIT_CARD_ID)
	,CONSTRAINT PK_CUST_CC PRIMARY KEY(CUSTOMER_ACCOUNT_ID,CREDIT_CARD_ID)
)

CREATE TABLE FINANCIAL_DEPOSIT.tb_PAYMENT_TYPE
(
	PAYMENT_TYPE_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL
	,PAYMENT_TYPE VARCHAR(20) NOT NULL
	,IS_ACTIVE BIT NOT NULL DEFAULT 1
	,IS_DELETED BIT DEFAULT 0
	,LAST_MODIFIED_BY VARCHAR(50) NULL
	,LAST_MODIFIED_DATE DATETIME NULL
)

CREATE TABLE FINANCIAL_DEPOSIT.tb_CURRENCY
(
	 CURRENCY_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL
	,CURRENCY_NAME VARCHAR(15) NOT NULL
)

CREATE TABLE FINANCIAL_DEPOSIT.tb_EVENT_TYPES
(
	EVENT_TYPE_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL
	,EVENT_TYPE VARCHAR(20) NOT NULL
)

CREATE TABLE FINANCIAL_DEPOSIT.tb_EVENTS
(
	EVENT_ID INT PRIMARY KEY IDENTITY(1000,1) NOT NULL
	,CLIENT_ID INT NOT NULL
	,EVENT_TYPE_ID INT NOT NULL
	,CUSTOMER_ACCOUNT_ID INT NOT NULL
	,AMOUNT NUMERIC(18,10) NOT NULL
	,PAYMENT_TYPE_ID INT NOT NULL
	,CURRENCY_ID INT NOT NULL
	,SUBMITTED_DATE DATETIME NOT NULL
	,IS_ACTIVE BIT NOT NULL DEFAULT 1
	,IS_DELETED BIT DEFAULT 0
	,LAST_MODIFIED_BY VARCHAR(50) NULL
	,LAST_MODIFIED_DATE DATETIME NULL
	,CONSTRAINT FK_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLI_COMMON.tb_CLIENTS(CLIENT_ID)
	,CONSTRAINT FK_CUST_ID FOREIGN KEY (CUSTOMER_ACCOUNT_ID) REFERENCES CUSTOMERS.tb_CUSTOMER_ACCOUNTS(CUSTOMER_ACCOUNT_ID)
	,CONSTRAINT FK_PAYMENT_ID FOREIGN KEY (PAYMENT_TYPE_ID) REFERENCES FINANCIAL_DEPOSIT.tb_PAYMENT_TYPE(PAYMENT_TYPE_ID)
	,CONSTRAINT FK_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES FINANCIAL_DEPOSIT.tb_CURRENCY (CURRENCY_ID)
	,CONSTRAINT FK_EVENT_TYPE_ID FOREIGN KEY (EVENT_TYPE_ID) REFERENCES FINANCIAL_DEPOSIT.tb_EVENT_TYPES (EVENT_TYPE_ID)
)