--id, nombre completo, telefono mas reciente

USE [IF5100_2022_B76090]
GO

SELECT [CUSTOMER_ACCOUNT_ID]
      ,[CLIENT_ID]
      ,[CUSTOMER_NAME]+' '+[CUSTOMER_LAST_NAME]
  FROM [CUSTOMERS].[tb_CUSTOMER_ACCOUNTS]
  CROSS APPLY [CUSTOMERS].tb_PHONE
GO
