/* 
	CONSULTA PEGADA EN UNA TRANSACCION INSERTANDO UN REGISTRO
	COMO ES UNA TRANSACCION SE BLOQUEA EL RECURSO

	Y NUESTRA CONSULTA NO SE BLOQUEA CON EL (NOLOCK)
	ESTA ES UNA CONSULTA SUCIA PORQUE EN REALIDAD NO SE CREO EL REGISTRO

	(NOLOCK) NO ADMITE BLOQUEOS NI NADA, SOLO DA LO QUE ESTE DISPONIBLE
*/
SELECT TOP (1000) [CUSTOMER_ACCOUNT_ID]
      ,[CLIENT_ID]
      ,[CUSTOMER_NAME]
      ,[CUSTOMER_LAST_NAME]
      ,[IS_ACTIVE]
      ,[IS_DELETED]
      ,[LAST_MODIFY_BY]
      ,[LAST_MODIFY_DATE]
  FROM [IF5100_2022_B94511].[CUSTOMERS].[tb_CUSTOMER_ACCOUNTS] (NOLOCK) --HINT DE SQL
where [CUSTOMER_NAME] = 'PruebaNombre'

/*
TAREA

CUANTOS HINSTS EN SQL 
LAS MAS USADAS
CONSULTAS FANTASMAS

*/