CREATE PROCEDURE sp_COBRO_NETFLIX(@USUARIO VARCHAR(50), @CANTIDAD FLOAT)
/**
*	@USUARIO: USUARIO AL CUAL SE LE VA A HACER EL REBAJO
*	@CANTIDAD: DINERO QUE SE LE SACARA DE LA CUENTA
*/

AS
BEGIN
	DECLARE @saldoInicial float

	/**
	*	LEE EL RECURSO
	*/
	SET @saldoInicial = (SELECT
		DINERO
	FROM CUENTA_BANCARIA
	WHERE USUARIO = @USUARIO)

	/**
	*	ESPERA POR 5 SEGUNDOS SIN RESERVAR EL RECURSO
	*/
	WAITFOR DELAY '00:00:05'

	/**
	*	ACTUALIZA EL SALDO DE LA CUENTA
	*/
	UPDATE [dbo].[CUENTA_BANCARIA]
	   SET [DINERO] = @saldoInicial - @CANTIDAD
	 WHERE USUARIO = @USUARIO

	SELECT * FROM CUENTA_BANCARIA
END
GO
