CREATE PROCEDURE sp_TRANSFERENCIA_SALARIO (@USUARIO VARCHAR(50), @CANTIDAD FLOAT)
/**
*	@USUARIO: USUARIO AL CUAL SE LE VA A HACER EL DEPOSITO
*	@CANTIDAD: DINERO QUE SE LE DEPOSITARA A LA CUENTA
*/

AS
BEGIN
	DECLARE @saldoInicial float

	/**
	*	LEE EL RECURSO
	*/
	SET @saldoInicial = (SELECT
		DINERO
	FROM CUENTA_BANCARIA
	WHERE USUARIO = @USUARIO)
	
	/**
	*	ESPERA POR 10 SEGUNDOS SIN RESERVAR EL RECURSO
	*/
	WAITFOR DELAY '00:00:10'

	/**
	*	ACTUALIZA EL SALDO DE LA CUENTA
	*/
	UPDATE [dbo].[CUENTA_BANCARIA]
	   SET [DINERO] = @saldoInicial + @CANTIDAD
	 WHERE USUARIO = @USUARIO

	SELECT * FROM CUENTA_BANCARIA
END
GO
