
ALTER SERVER AUDIT [Security_Audit] WITH (STATE = ON)
GO

BACKUP DATABASE [Testing]
TO DISK='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\TestAudit.bak'

USE [Testing]
INSERT INTO [MOCKS].[MOCK_DATA_FIRST_NAMES]
(id, first_name)
VALUES
(501, 'JACINTO')

INSERT INTO [MOCKS].[MOCK_DATA_LAST_NAMES]
(id, last_name)
VALUES
(501, 'BASURILLA')

UPDATE [MOCKS].[MOCK_DATA_FIRST_NAMES]
   SET [first_name] = 'Jacinto'
 WHERE id = 501

SELECT * FROM [MOCKS].[MOCK_DATA_FIRST_NAMES] ORDER BY id DESC
SELECT * FROM [MOCKS].[MOCK_DATA_LAST_NAMES] ORDER BY id DESC

DELETE FROM [MOCKS].[MOCK_DATA_FIRST_NAMES]
      WHERE id = 501

DELETE FROM [MOCKS].[MOCK_DATA_LAST_NAMES]
      WHERE id = 501
