USE [IF5100_PRUEBA_INDICES_B76090]

GO

CREATE NONCLUSTERED INDEX [ix_NonClusterIndex_Birthday] 
ON [IF5100].[tb_PERSON]
(
	[BIRTHDAY] ASC
)WITH (PAD_INDEX = OFF,
STATISTICS_NORECOMPUTE = OFF,
SORT_IN_TEMPDB = OFF,
DROP_EXISTING = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON)

GO


