CREATE DATABASE IF5100_PRUEBA_INDICES_B76090

USE IF5100_PRUEBA_INDICES_B76090

CREATE SCHEMA IF5100

CREATE TABLE IF5100.tb_PERSON
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    BIRTHDAY DATETIME,
	IS_ACTIVE BIT DEFAULT 1,
	ADDRESS VARCHAR(100)
)

DECLARE @local_X INT = 1

WHILE(@local_X <= 1000000)
BEGIN
	INSERT INTO IF5100.tb_PERSON
	(
		NAME, LAST_NAME, BIRTHDAY, ADDRESS
	)
	SELECT 
		'NAME' + CAST(CONVERT(varchar(255), NEWID()) AS VARCHAR(50)),
		'LASNAME' + CAST(CONVERT(varchar(255), NEWID()) AS VARCHAR(50)),
		DATEADD(DAY, (ABS(CHECKSUM(NEWID())) % 65530), 0),
		'ADDRESS' + CAST(CONVERT(varchar(255), NEWID()) AS VARCHAR(50))
	SELECT @local_X = @local_X + 1
END

SELECT * FROM [IF5100].[tb_PERSON]