USE IF5100_2022_B76090

INSERT INTO [FINANCIAL_DEPOSIT].[tb_EVENT_TYPES]
(EVENT_TYPE)
VALUEs
('Compra'),
('Retiro'),
('Deposito')

SELECT * FROM [FINANCIAL_DEPOSIT].[tb_EVENT_TYPES]

USE [IF5100_2022_B76090]
GO

INSERT INTO [FINANCIAL_DEPOSIT].[tb_EVENT_TYPES]
           ([EVENT_TYPE])
     VALUES
           ('SINPE')
GO

