USE IF5100_2022_B76090

CREATE TABLE FINANCIAL_DEPOSIT.tb_ERROR
(
	ERROR_ID INT IDENTITY(1,1) PRIMARY KEY,
	CUSTOMER_ACCOUNT_SOURCE INT,
	CUSTOMER_ACCOUNT_DESTINATION INT,
	ERRORNUMBER INT DEFAULT ERROR_NUMBER(),
	ERRORSTATE INT DEFAULT ERROR_STATE(),
	ERRORSEVERITY INT DEFAULT ERROR_SEVERITY(), 
	ERROR_DESCRIPTION VARCHAR(200) DEFAULT ERROR_MESSAGE(),
	EVENT_TYPE INT NOT NULL,
	LAST_MODIFICATION_BY VARCHAR(50) DEFAULT SUSER_NAME(),
	LAST_MODIFICATION_DATE VARCHAR(50) DEFAULT GETDATE()
)