
CREATE TABLE CUSTOMERS.tb_BALANCE
(
	[CUSTOMER_ACCOUNT_ID] INT PRIMARY KEY,
	ID_CLIENT INT,
	BALANCE NUMERIC(9,3),
	CONSTRAINT fk_CUSTOMER_ACCOUNT_ID_BAL FOREIGN KEY (CUSTOMER_ACCOUNT_ID) 
		REFERENCES CUSTOMERS.tb_CUSTOMER_ACCOUNTS(CUSTOMER_ACCOUNT_ID),
	CONSTRAINT fk_CLIENT_ID FOREIGN KEY (ID_CLIENT)
		REFERENCES CLI_COMMON.tb_CLIENTS(CLIENT_ID)
)