CREATE TABLE FINANCIAL_DEPOSIT.tb_ERROR
(
	ERROR_ID INT IDENTITY(1,1) PRIMARY KEY,
	CUSTOMER_ACCOUNT_SOURCE INT,
	CUSTOMER_ACCOUNT_DESTINATION INT,
	ERROR_DESCRIPTION VARCHAR(100),
	EVENT_ID INT NOT NULL,
	LAST_MODIFICATION_BY VARCHAR(50) DEFAULT SUSER_NAME(),
	LAST_MODIFICATION_DATE VARCHAR(50) DEFAULT GETDATE()
)