USE IF5100_2022_B76090

CREATE TABLE CUSTOMERS.tb_BALANCE
(
	[CUSTOMER_ACCOUNT_ID] INT PRIMARY KEY,
	ID_CLIENT INT,
	BALANCE NUMERIC(9,3),
	CONSTRAINT fk_CUSTOMER_ACCOUNT_ID_BAL FOREIGN KEY (CUSTOMER_ACCOUNT_ID) 
		REFERENCES CUSTOMERS.tb_CUSTOMER_ACCOUNTS(CUSTOMER_ACCOUNT_ID),
	CONSTRAINT fk_CLIENT_ID FOREIGN KEY (ID_CLIENT)
		REFERENCES CLI_COMMON.tb_CLIENTS(CLIENT_ID)
)

USE [IF5100_2022_B76090]
GO

INSERT INTO [CUSTOMERS].[tb_BALANCE]
           ([CUSTOMER_ACCOUNT_ID]
           ,[ID_CLIENT]
           ,[BALANCE])
     VALUES
           (1,1003,10000),
		   (2,1001,10000)
GO


select * from [CUSTOMERS].[tb_BALANCE]
select * from [CUSTOMERS].[tb_CUSTOMER_ACCOUNTS]


BEGIN TRANSACTION
USE [IF5100_2022_B76090]
GO
	DECLARE @intCustomerAccount INT = 3

	WHILE(@intCustomerAccount < 102)
	BEGIN
		
		INSERT INTO [CUSTOMERS].[tb_BALANCE]
           ([CUSTOMER_ACCOUNT_ID]
           ,[ID_CLIENT]
           ,[BALANCE])
		VALUES
           ((SELECT CUSTOMER_ACCOUNT_ID FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_ACCOUNT_ID = @intCustomerAccount)
           ,(SELECT CLIENT_ID FROM CUSTOMERS.tb_CUSTOMER_ACCOUNTS WHERE CUSTOMER_ACCOUNT_ID = @intCustomerAccount)
           ,10000)

		SET @intCustomerAccount = @intCustomerAccount + 1
	END
GO

COMMIT