USE IF5100_2022_B76090

CREATE TABLE dbo.tb_CUSTOMER_ACCOUNTS_HISTORY
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ACTIONS VARCHAR(25),
	COLUMNA VARCHAR(200),
	OLD_NAME VARCHAR(25),
	NEW_NAME VARCHAR(25),
	OLD_LASTNAME VARCHAR(25),
	NEW_LASTNAME VARCHAR(25),
	OLD_CLIENT INT,
	NEW_CLIENT INT,
	LAST_MODIFIED_BY VARCHAR(25) DEFAULT SUSER_NAME(),
	LAST_MODIFIED_DATE DATETIME DEFAULT GETDATE()
)

CREATE TRIGGER tr_CustomerAccounts
	ON [CUSTOMERS].[tb_CUSTOMER_ACCOUNTS]
	FOR INSERT, DELETE, UPDATE  
	AS 
		DECLARE @ACTION VARCHAR(25)

		IF EXISTS (SELECT 0 FROM inserted)
		BEGIN
		   IF EXISTS (SELECT 0 FROM deleted)
		   BEGIN 
			  SELECT @ACTION = 'UPDATE'
		   BEGIN
			  SELECT @ACTION = 'INSERT'
		   END
		END ELSE 
		BEGIN
		   SELECT @ACTION = 'DELETE'
		END
		SELECT @ACTION
		BEGIN TRY
			IF(@ACTION = 'UPDATE' OR @ACTION = 'INSERT')
			BEGIN
				BEGIN TRANSACTION
					INSERT INTO dbo.tb_CUSTOMER_ACCOUNTS_HISTORY
					(
						ACTIONS
						,COLUMNA
						,OLD_NAME
						,NEW_NAME
						,OLD_LASTNAME
						,NEW_LASTNAME
						,OLD_CLIENT
						,NEW_CLIENT
					)
					SELECT
						@ACTION,
						COLUMNS_UPDATED(),
						CA.CUSTOMER_NAME,
						ins.CUSTOMER_NAME,
						CA.CUSTOMER_LAST_NAME,
						ins.CUSTOMER_LAST_NAME,
						CA.CLIENT_ID,
						ins.CLIENT_ID
					FROM inserted ins
						JOIN CUSTOMERS.tb_CUSTOMER_ACCOUNTS CA
						ON ins.CUSTOMER_ACCOUNT_ID = CA.CUSTOMER_ACCOUNT_ID

				COMMIT
			END
			ELSE
			BEGIN
				BEGIN TRANSACTION
					INSERT INTO dbo.tb_CUSTOMER_ACCOUNTS_HISTORY
					(
						ACTIONS
						,COLUMNA
						,OLD_NAME
						,NEW_NAME
						,OLD_LASTNAME
						,NEW_LASTNAME
						,OLD_CLIENT
						,NEW_CLIENT
					)
					SELECT
						@ACTION,
						COLUMNS_UPDATED(),
						CA.CUSTOMER_NAME,
						del.CUSTOMER_NAME,
						CA.CUSTOMER_LAST_NAME,
						del.CUSTOMER_LAST_NAME,
						CA.CLIENT_ID,
						del.CLIENT_ID
					FROM deleted del
						JOIN CUSTOMERS.tb_CUSTOMER_ACCOUNTS CA
						ON del.CUSTOMER_ACCOUNT_ID = CA.CUSTOMER_ACCOUNT_ID

				COMMIT
			END
        END TRY
        BEGIN CATCH
			ROLLBACK
			SELECT ERROR_MESSAGE()
        END CATCH
END





/*
* TEST
*/

SELECT TOP 1 * FROM [CUSTOMERS].[tb_CUSTOMER_ACCOUNTS] ORDER BY LAST_MODIFIED_DATE DESC

INSERT INTO [CUSTOMERS].[tb_CUSTOMER_ACCOUNTS]
(
	[CLIENT_ID], [CUSTOMER_NAME], [CUSTOMER_LAST_NAME]
)VALUES 
(
	1003, 'Paquito3', 'Juarez3'
)

SELECT * FROM dbo.tb_CUSTOMER_ACCOUNTS_HISTORY